---
name: "🔥 Feature"
description: "진행할 작업을 상세하게 기록해주세요."
title: "[Feature]: "
labels: ["enhancement"]
assignees: ""
---

<!-- Do not leave any section empty. -->

# 1. Executive Summary
<!--
    Executive Summary should contain about up to 3 paragraphs to clarify what
    happened. Bear in mind that this is targeted for Business Users as well,
    meaning technical details should be kept minimal.

    This is a REQUIRED field.
-->
